# Generated by Django 2.2.9 on 2019-12-27 09:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseresumepage',
            name='resume',
            field=wagtail.fields.StreamField([('work_experience', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(default='Work experience')), ('fa_icon', wagtail.blocks.CharBlock(default='fas fa-tools')), ('experiences', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('role', wagtail.blocks.CharBlock()), ('company', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock()), ('from_date', wagtail.blocks.DateBlock()), ('to_date', wagtail.blocks.DateBlock()), ('text', wagtailmarkdown.blocks.MarkdownBlock())], icon='folder-open-inverse')))])), ('contributions', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(default='Contributions')), ('fa_icon', wagtail.blocks.CharBlock(default='fas fa-code-branch')), ('contributions', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock()), ('url', wagtail.blocks.URLBlock())], icon='folder-open-inverse')))])), ('writing', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(default='Writing')), ('fa_icon', wagtail.blocks.CharBlock(default='fas fa-pencil-alt')), ('posts', wagtail.blocks.StreamBlock([('internal_post', wagtail.blocks.StructBlock([('post', wagtail.blocks.PageChooserBlock())], icon='doc-full-inverse')), ('external_post', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock()), ('date', wagtail.blocks.DateBlock())], icon='doc-full-inverse'))], icon='folder-open-inverse'))]))], blank=True, null=True),
        ),
    ]
