# Generated by Django 2.2.9 on 2020-01-10 16:56

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_resume', '0003_auto_20200110_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseresumepage',
            name='about',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, max_length=2500, null=True),
        ),
    ]
