# Generated by Django 3.2.6 on 2022-01-12 18:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_resume', '0005_auto_20200227_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseresumepage',
            name='social_links',
            field=wagtail.core.fields.StreamField([('social_link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('url', wagtail.core.blocks.URLBlock()), ('logo', wagtail.images.blocks.ImageChooserBlock(required=False))], icon='group'))], blank=True, null=True),
        ),
    ]
