# Generated by Django 3.2.12 on 2022-02-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_resume', '0006_alter_baseresumepage_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresumepage',
            name='pdf_generation_visibility',
            field=models.CharField(choices=[('always', 'Always visible'), ('authenticated', 'Only logged in users'), ('never', 'Never visible')], default='logged_in', help_text='\n            PDF generation is a heavy blocking operation,\n            so it is recommended to only show it to logged in users. If available to everyone, ensure that you have multiple workers running.\n        ', max_length=64),
        ),
    ]
