# Generated by Django 4.1.2 on 2022-10-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_resume", "0008_auto_20220211_1557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseresumepage",
            name="pdf_generation_visibility",
            field=models.CharField(
                choices=[
                    ("always", "Always visible"),
                    ("authenticated", "Only logged in users"),
                    ("never", "Never visible"),
                ],
                default="authenticated",
                help_text="\n            PDF generation is a heavy blocking operation,\n            so it is recommended to only show it to logged in users.\n            If available to everyone, ensure that you have multiple workers running.\n        ",
                max_length=64,
            ),
        ),
    ]
