# Generated by Django 5.0.2 on 2024-04-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_resume", "0013_alter_baseresumepage_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseresumepage",
            name="display_last_update",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, the last update date will be displayed.",
            ),
        ),
    ]
