# yamllint disable rule:line-length rule:truthy
---
name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: write  # for release-drafter/release-drafter to create a github release
  pull-requests: write  # for release-drafter/release-drafter to add label to PR

jobs:
  update_pr_labels:
    name: Update PR Labels
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:

      - uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: false
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_release_draft:
    name: Update Release Draft
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      PUBLISH_DRAFT: false
    steps:

      - name: Check if a version is cut
        if: "contains(github.event.head_commit.message, 'chore(prerelease): Cut Version')"
        run: |
          echo "PUBLISH_DRAFT=true" >> $GITHUB_ENV

      # Drafts your next Release notes
      - uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: true
          disable-releaser: false
          publish: ${{ env.PUBLISH_DRAFT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
