# yamllint disable rule:line-length rule:truthy
---
name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions: read-all

jobs:
  update_pr_labels:
    name: Update PR Labels
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # for release-drafter to add labels to PR
    steps:
      - uses: release-drafter/release-drafter/autolabeler@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_release_draft:
    name: Update Release Draft
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write # for release-drafter to create/update release draft
      pull-requests: read # for release-drafter to read PR data associated with commits
    env:
      PUBLISH_DRAFT: false
    steps:
      - name: Check if a version is cut
        if: "contains(github.event.head_commit.message, 'chore(prerelease): Cut Version')"
        run: |
          echo "PUBLISH_DRAFT=true" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        with:
          publish: ${{ env.PUBLISH_DRAFT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
